//constantes
export const GET_CHARACTERS_REQUEST = 'GET_CHARACTERS_REQUEST'
 
export const GET_CHARACTER_ID_REQUEST = 'GET_CHARACTER_ID_REQUEST'
 
export const FAVORITE_CHARACTER = 'FAVORITE_CHARACTER'

export const ELIMINATE_FAVORITE_CHARACTER = 'ELIMINATE_FAVORITE_CHARACTER'